version: '3.8'
services:
  postgres:
    image: postgres:14
    restart: always
    container_name: sweetbakery-backend-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres_fallback}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - ${DB_PORT:-5432}:5432
